import type { EquipmentDefinition, EquipmentKind } from '../domain/types'

export const EQUIPMENT: Record<EquipmentKind, EquipmentDefinition> = {
  'boxing-ring': {
    kind: 'boxing-ring',
    name: 'Competition boxing ring',
    category: 'Structures',
    dimensions: [7.8, 8.7, 2.3],
    clearance: 1,
    description: '7.8 × 8.7 m planning footprint with steps · 6.1 m inside ropes',
  },
  'mma-cage': {
    kind: 'mma-cage',
    name: 'MMA octagon',
    category: 'Structures',
    dimensions: [11.6, 11.6, 2.95],
    clearance: 1,
    description: '11.6 m planning footprint with steps · 9 m inside · 1.95 m fence',
  },
  'wrestling-circle': {
    kind: 'wrestling-circle',
    name: 'Wrestling competition circle',
    category: 'Floor Markings',
    dimensions: [10, 10, 0.01],
    clearance: 0,
    description: 'Movable UWW 9 m circle · 10 × 10 m planning bay',
  },
  'heavy-bag': {
    kind: 'heavy-bag',
    name: 'Classic heavy bag',
    category: 'Heavy Bags',
    dimensions: [0.42, 0.42, 1.5],
    clearance: 1.25,
    description: '42 cm diameter · 150 cm body',
  },
  'banana-bag': {
    kind: 'banana-bag',
    name: 'Muay Thai banana bag',
    category: 'Heavy Bags',
    dimensions: [0.36, 0.36, 1.8],
    clearance: 1.35,
    description: '36 cm diameter · 180 cm body',
  },
  'banana-bag-xl': {
    kind: 'banana-bag-xl',
    name: 'Extra large banana bag',
    category: 'Heavy Bags',
    dimensions: [0.55, 0.55, 2],
    clearance: 1.5,
    description: '55 cm diameter · 200 cm body',
  },
  'teardrop-bag': {
    kind: 'teardrop-bag',
    name: 'Teardrop bag',
    category: 'Heavy Bags',
    dimensions: [0.58, 0.58, 1.05],
    clearance: 1.25,
    description: '58 cm widest point · 105 cm body',
  },
  'double-end-25x18': {
    kind: 'double-end-25x18',
    name: 'Double-end bag · Small',
    category: 'Double-End Bags',
    dimensions: [0.18, 0.18, 0.25],
    clearance: 1.2,
    description: '25 cm high · 18 cm diameter',
  },
  'double-end-30x20': {
    kind: 'double-end-30x20',
    name: 'Double-end bag · Medium',
    category: 'Double-End Bags',
    dimensions: [0.2, 0.2, 0.3],
    clearance: 1.25,
    description: '30 cm high · 20 cm diameter',
  },
  'double-end-35x22': {
    kind: 'double-end-35x22',
    name: 'Double-end bag · Large',
    category: 'Double-End Bags',
    dimensions: [0.22, 0.22, 0.35],
    clearance: 1.3,
    description: '35 cm high · 22 cm diameter',
  },
  'speed-bag-18x13': {
    kind: 'speed-bag-18x13',
    name: 'Speed bag · XS',
    category: 'Speed Bags',
    dimensions: [0.13, 0.13, 0.18],
    clearance: 0.85,
    description: '18 cm high · 13 cm diameter',
  },
  'speed-bag-20x15': {
    kind: 'speed-bag-20x15',
    name: 'Speed bag · Small',
    category: 'Speed Bags',
    dimensions: [0.15, 0.15, 0.2],
    clearance: 0.9,
    description: '20 cm high · 15 cm diameter',
  },
  'speed-bag-23x18': {
    kind: 'speed-bag-23x18',
    name: 'Speed bag · Medium',
    category: 'Speed Bags',
    dimensions: [0.18, 0.18, 0.23],
    clearance: 0.95,
    description: '23 cm high · 18 cm diameter',
  },
  'speed-bag-25x20': {
    kind: 'speed-bag-25x20',
    name: 'Speed bag · Large',
    category: 'Speed Bags',
    dimensions: [0.2, 0.2, 0.25],
    clearance: 1,
    description: '25 cm high · 20 cm diameter',
  },
  'speed-bag-28x22': {
    kind: 'speed-bag-28x22',
    name: 'Speed bag · XL',
    category: 'Speed Bags',
    dimensions: [0.22, 0.22, 0.28],
    clearance: 1.05,
    description: '28 cm high · 22 cm diameter',
  },
  'hb2-classic': {
    kind: 'hb2-classic',
    name: 'HB2 Classic heavy bag',
    category: 'Black Leather Bags',
    dimensions: [0.33, 0.33, 0.9],
    clearance: 1.2,
    description: '33 cm diameter · 90 cm body',
  },
  'hb3-extra-large': {
    kind: 'hb3-extra-large',
    name: 'HB3 Extra large heavy bag',
    category: 'Black Leather Bags',
    dimensions: [0.4, 0.4, 1],
    clearance: 1.3,
    description: '40 cm diameter · 100 cm body',
  },
  'hb5-4ft': {
    kind: 'hb5-4ft',
    name: 'HB5 4FT heavy bag',
    category: 'Black Leather Bags',
    dimensions: [0.34, 0.34, 1.21],
    clearance: 1.25,
    description: '34 cm diameter · 121 cm body',
  },
  'hb6-6ft-banana': {
    kind: 'hb6-6ft-banana',
    name: 'HB6 6FT Muay Thai banana bag',
    category: 'Black Leather Bags',
    dimensions: [0.36, 0.36, 1.8],
    clearance: 1.35,
    description: '36 cm diameter · 180 cm body',
  },
  'hb7-pole': {
    kind: 'hb7-pole',
    name: 'HB7 7FT pole bag',
    category: 'Black Leather Bags',
    dimensions: [0.59, 0.59, 2.7],
    clearance: 1.6,
    description: '59 cm diameter · 270 cm overall',
  },
  'hb10-bowling': {
    kind: 'hb10-bowling',
    name: 'HB10 Bowling bag',
    category: 'Black Leather Bags',
    dimensions: [0.5, 0.5, 1.22],
    clearance: 1.35,
    description: '50 cm widest point · 122 cm body',
  },
  'hb11-uppercut': {
    kind: 'hb11-uppercut',
    name: 'HB11 Uppercut bag',
    category: 'Black Leather Bags',
    dimensions: [0.5, 0.5, 0.58],
    clearance: 1.3,
    description: '50 cm widest point · 58 cm body',
  },
  'hb12-angle': {
    kind: 'hb12-angle',
    name: 'HB12 Angle heavy bag',
    category: 'Black Leather Bags',
    dimensions: [0.5, 0.5, 1.47],
    clearance: 1.4,
    description: '50 cm widest point · 147 cm body',
  },
  'hb13-super-angle': {
    kind: 'hb13-super-angle',
    name: 'HB13 Super angle heavy bag',
    category: 'Black Leather Bags',
    dimensions: [0.5, 0.5, 1.37],
    clearance: 1.45,
    description: '50 cm widest point · 137 cm body',
  },
  'hb15-super-teardrop': {
    kind: 'hb15-super-teardrop',
    name: 'HB15 Super tear drop heavy bag',
    category: 'Black Leather Bags',
    dimensions: [0.38, 0.38, 0.93],
    clearance: 1.3,
    description: '38 cm widest point · 93 cm body',
  },
  'hb16-water': {
    kind: 'hb16-water',
    name: 'HB16 Water heavy bag',
    category: 'Black Leather Bags',
    dimensions: [0.46, 0.46, 0.58],
    clearance: 1.25,
    description: '46 cm widest point · 58 cm body',
  },
  'uc1-wall-unit': {
    kind: 'uc1-wall-unit',
    name: 'UC1 Uppercut & hook wall unit',
    category: 'Black Leather Bags',
    dimensions: [0.58, 0.4, 0.7],
    clearance: 1.5,
    description: '58 cm wide · 70 cm high · wall mounted',
  },
  'maddox-iii-dummy': {
    kind: 'maddox-iii-dummy',
    name: 'Maddox III hybrid training dummy',
    category: 'Black Leather Bags',
    dimensions: [0.75, 0.75, 1.65],
    clearance: 1.5,
    description: '165 cm high · 75 cm planning base',
  },
  'bag-rack-1': {
    kind: 'bag-rack-1',
    name: 'Heavy bag rack · 1 station',
    category: 'Bag Racks',
    dimensions: [1.78, 1.55, 2.24],
    clearance: 1.25,
    description: 'Empty commercial stand · 1 mount',
  },
  'bag-rack-2': {
    kind: 'bag-rack-2',
    name: 'Build your own rack',
    category: 'Bag Racks',
    dimensions: [3.2, 1.55, 2.44],
    clearance: 1.25,
    description: 'Choose 1–20 stations, then assign each bag separately',
  },
  'bag-rack-3': {
    kind: 'bag-rack-3',
    name: 'Heavy bag rack · 3 stations',
    category: 'Bag Racks',
    dimensions: [2.7, 2.7, 2.44],
    clearance: 1.25,
    description: 'Empty 3-arm commercial circuit tree',
  },
  'bag-rack-4': {
    kind: 'bag-rack-4',
    name: 'Heavy bag rack · 4 stations',
    category: 'Bag Racks',
    dimensions: [1.83, 1.83, 2.44],
    clearance: 1.25,
    description: 'Empty 360° frame · 4 independent mounts',
  },
  'speed-bag-platform': {
    kind: 'speed-bag-platform',
    name: 'Adjustable speed bag platform',
    category: 'Bag Racks',
    dimensions: [0.82, 1.15, 2.35],
    clearance: 1,
    description: 'Empty drum and swivel · adjustable height',
  },
  'double-end-system': {
    kind: 'double-end-system',
    name: 'Floor-to-ceiling double-end anchors',
    category: 'Bag Racks',
    dimensions: [0.32, 0.32, 3],
    clearance: 1.3,
    description: 'Empty paired anchors · ceiling height planning',
  },
  bench: {
    kind: 'bench',
    name: 'Training bench',
    category: 'Facilities',
    dimensions: [1.5, 0.48, 0.48],
    clearance: 0.5,
    description: '1.5 × 0.48 m fixed footprint',
  },
  'equipment-rack': {
    kind: 'equipment-rack',
    name: 'Equipment rack',
    category: 'Pads and Storage',
    dimensions: [1.8, 0.55, 1.9],
    clearance: 0.75,
    description: '1.8 × 0.55 × 1.9 m',
  },
  'reception-counter': {
    kind: 'reception-counter',
    name: 'Reception counter',
    category: 'Facilities',
    dimensions: [2.4, 0.75, 1.15],
    clearance: 0.9,
    description: '2.4 m commercial welcome desk',
  },
  'wall-pads': {
    kind: 'wall-pads',
    name: 'Wall pad section',
    category: 'Facilities',
    dimensions: [2.4, 0.12, 1.8],
    clearance: 0.35,
    description: '2.4 m modular padded section',
  },
}

export const CATEGORIES = [...new Set(Object.values(EQUIPMENT).map((item) => item.category))]
