export const ATHLETONIC_SOURCE_OF_TRUTH = {
  marketplace: {
    name: "Athletonic",
    domain: "athletonic.com",
    country: "United States",
    currency: "USD",
    businessModel:
      "US-first performance store for supplements, sports nutrition, fitness apparel, recovery, footwear, and training accessories.",
  },

  brandPalette: {
    deepBlue: "#0B1F3A",
    modernTeal: "#2EC4B6",
    white: "#FFFFFF",
    lightGray: "#F5F7FA",
    ink: "#102033",
    muted: "#607084",
    line: "#DDE5EF",
  },

  pagePalettes: {
    home: {
      background: "#F5F7FA",
      header: "#0B1F3A",
      accent: "#2EC4B6",
      surface: "#FFFFFF",
      text: "#102033",
    },
    shop: {
      background: "#F5F7FA",
      header: "#0B1F3A",
      accent: "#2EC4B6",
      surface: "#FFFFFF",
      text: "#102033",
    },
    brands: {
      background: "#F5F7FA",
      header: "#0B1F3A",
      accent: "#2EC4B6",
      surface: "#FFFFFF",
      text: "#102033",
    },
    deals: {
      background: "#F5F7FA",
      header: "#0B1F3A",
      accent: "#2EC4B6",
      surface: "#FFFFFF",
      text: "#102033",
    },
  },

  featuredBrandSlugs: [
    "optimum_nutrition",
    "ghost_lifestyle",
    "gorilla_mind",
    "raw_nutrition",
    "cellucor",
    "transparent_labs",
    "kaged",
    "first_phorm",
    "liquid_iv",
    "nuun",
    "skratch_labs",
    "thorne",
    "garden_of_life",
    "ritual",
    "maryruth_organics",
    "goli",
    "nike",
    "allbirds",
    "ten_thousand",
    "outdoor_voices",
    "bear_komplex",
    "trx",
    "harbinger",
    "schiek",
    "therabody",
    "hyperice",
    "compex",
    "manta_sleep",
  ],

  sourcePolicy: {
    productDataSource: "/Users/User/Desktop/Sups/output/data/products.db",
    acceptedCountry: "United States",
    acceptedCurrency: "USD",
    productFields:
      "Product names, URLs, images, availability, and prices must come from each brand's official website/domain.",
    priceRule:
      "Prices shown on Athletonic must come only from the official US/official brand domain. Retailer, reseller, foreign-market, affiliate, or aggregator prices are not valid.",
    blockedSourceDomains: [
      "bodyandfit.com",
      "bodyscience.com.au",
      "bodybuilding.com",
      "discount-supplements.co.uk",
      "nutritionwarehouse.com.au",
      "nzmuscle.co.nz",
      "supplementmart.com.au",
      "supplementsource.ca",
      "suppz.com",
      "swansonvitamins.com",
      "thefeed.com",
      "tigerfitness.com",
    ],
  },

  brands: [
    { slug: "agent_nateur", name: "Agent Nateur", officialDomains: ["agentnateur.com"] },
    { slug: "allbirds", name: "Allbirds", officialDomains: ["allbirds.com"] },
    { slug: "alpha_lion", name: "Alpha Lion", officialDomains: ["alphalion.com"] },
    { slug: "amazing_grass", name: "Amazing Grass", officialDomains: ["amazinggrass.com"] },
    { slug: "animal_pak", name: "Animal", officialDomains: ["animalpak.com"] },
    { slug: "armra", name: "ARMRA", officialDomains: ["tryarmra.com"] },
    { slug: "bare_performance", name: "Bare Performance", officialDomains: ["bareperformancenutrition.com"] },
    { slug: "bear_komplex", name: "Bear KompleX", officialDomains: ["bearkomplex.com"] },
    { slug: "bloom_nutrition", name: "Bloom Nutrition", officialDomains: ["bloomnu.com"] },
    { slug: "bsn", name: "BSN", officialDomains: ["bsnsupplements.com"] },
    { slug: "bucked_up", name: "Bucked Up", officialDomains: ["buckedup.com"] },
    { slug: "cellucor", name: "Cellucor", officialDomains: ["cellucor.com"] },
    { slug: "century_martial_arts", name: "Century Martial Arts", officialDomains: ["centurymartialarts.com"] },
    { slug: "codeage", name: "Codeage", officialDomains: ["codeage.com"] },
    { slug: "compex", name: "Compex", officialDomains: ["compex.com"] },
    { slug: "core_nutritionals", name: "Core Nutritionals", officialDomains: ["corenutritionals.com"] },
    { slug: "cure_hydration", name: "Cure Hydration", officialDomains: ["curehydration.com"] },
    { slug: "cymbiotika", name: "Cymbiotika", officialDomains: ["cymbiotika.com"] },
    { slug: "drip_drop", name: "DripDrop", officialDomains: ["dripdrop.com"] },
    { slug: "dymatize", name: "Dymatize", officialDomains: ["dymatize.com"] },
    { slug: "everlast", name: "Everlast", officialDomains: ["everlast.com"] },
    { slug: "fairtex", name: "Fairtex", officialDomains: ["fairtex.com"] },
    { slug: "first_phorm", name: "1st Phorm", officialDomains: ["1stphorm.com"] },
    { slug: "five_percent_nutrition", name: "5% Nutrition", officialDomains: ["5percentnutrition.com"] },
    { slug: "four_sigmatic", name: "Four Sigmatic", officialDomains: ["us.foursigmatic.com"] },
    { slug: "fuji_sports", name: "Fuji Sports", officialDomains: ["fujisports.com"] },
    { slug: "garden_of_life", name: "Garden of Life", officialDomains: ["gardenoflife.com"] },
    { slug: "ghost_lifestyle", name: "GHOST", officialDomains: ["ghostlifestyle.com"] },
    { slug: "goli", name: "Goli", officialDomains: ["goli.com"] },
    { slug: "gorilla_mind", name: "Gorilla Mind", officialDomains: ["gorillamind.com"] },
    { slug: "harbinger", name: "Harbinger", officialDomains: ["harbingerfitness.com"] },
    { slug: "hayabusa", name: "Hayabusa", officialDomains: ["hayabusafight.com"] },
    { slug: "huge_supplements", name: "Huge Supplements", officialDomains: ["hugesupplements.com"] },
    { slug: "hyperice", name: "Hyperice", officialDomains: ["hyperice.com"] },
    { slug: "inno_supps", name: "Inno Supps", officialDomains: ["innosupps.com"] },
    { slug: "iron_bull_strength", name: "Iron Bull Strength", officialDomains: ["ironbullstrength.com"] },
    { slug: "jacked_factory", name: "Jacked Factory", officialDomains: ["jackedfactory.com"] },
    { slug: "jocko_fuel", name: "Jocko Fuel", officialDomains: ["jockofuel.com"] },
    { slug: "kaged", name: "Kaged", officialDomains: ["kaged.com"] },
    { slug: "key_nutrients", name: "Key Nutrients", officialDomains: ["keynutrients.com"] },
    { slug: "kos", name: "KOS", officialDomains: ["kos.com"] },
    { slug: "liquid_iv", name: "Liquid I.V.", officialDomains: ["liquid-iv.com"] },
    { slug: "manta_sleep", name: "Manta Sleep", officialDomains: ["mantasleep.com"] },
    { slug: "maryruth_organics", name: "MaryRuth Organics", officialDomains: ["maryruthorganics.com"] },
    { slug: "momentous", name: "Momentous", officialDomains: ["livemomentous.com"] },
    { slug: "mud_wtr", name: "MUD/WTR", officialDomains: ["mudwtr.com"] },
    { slug: "muscletech", name: "MuscleTech", officialDomains: ["muscletech.com"] },
    { slug: "naked_nutrition", name: "Naked Nutrition", officialDomains: ["nakednutrition.com"] },
    { slug: "nike", name: "Nike", officialDomains: ["nike.com"] },
    { slug: "nordic_naturals", name: "Nordic Naturals", officialDomains: ["nordic.com"] },
    { slug: "now_foods", name: "NOW Foods", officialDomains: ["nowfoods.com"] },
    { slug: "nutrabio", name: "NutraBio", officialDomains: ["nutrabio.com"] },
    { slug: "nuun", name: "Nuun", officialDomains: ["nuunlife.com"] },
    { slug: "olly", name: "OLLY", officialDomains: ["olly.com"] },
    { slug: "onnit", name: "Onnit", officialDomains: ["onnit.com"] },
    { slug: "optimum_nutrition", name: "Optimum Nutrition", officialDomains: ["optimumnutrition.com"] },
    { slug: "orgain", name: "Orgain", officialDomains: ["orgain.com"] },
    { slug: "outdoor_voices", name: "Outdoor Voices", officialDomains: ["outdoorvoices.com"] },
    { slug: "owyn", name: "OWYN", officialDomains: ["liveowyn.com"] },
    { slug: "pescience", name: "PEScience", officialDomains: ["pescience.com"] },
    { slug: "primal_kitchen", name: "Primal Kitchen", officialDomains: ["primalkitchen.com"] },
    { slug: "promix", name: "Promix", officialDomains: ["promixnutrition.com"] },
    { slug: "pure_encapsulations", name: "Pure Encapsulations", officialDomains: ["pureencapsulationspro.com"] },
    { slug: "quest_nutrition", name: "Quest Nutrition", officialDomains: ["questnutrition.com"] },
    { slug: "raw_nutrition", name: "RAW Nutrition", officialDomains: ["getrawnutrition.com"] },
    { slug: "redcon1", name: "Redcon1", officialDomains: ["redcon1.com"] },
    { slug: "renue_by_science", name: "Renue By Science", officialDomains: ["renuebyscience.com"] },
    { slug: "ritual", name: "Ritual", officialDomains: ["ritual.com"] },
    { slug: "rival_boxing", name: "Rival Boxing", officialDomains: ["rivalboxing.us"] },
    { slug: "sanabul", name: "Sanabul", officialDomains: ["sanabulsports.com"] },
    { slug: "schiek", name: "Schiek", officialDomains: ["schiek.com"] },
    { slug: "skratch_labs", name: "Skratch Labs", officialDomains: ["skratchlabs.com"] },
    { slug: "soylent", name: "Soylent", officialDomains: ["soylent.com"] },
    { slug: "swolverine", name: "Swolverine", officialDomains: ["swolverine.com"] },
    { slug: "ten_thousand", name: "Ten Thousand", officialDomains: ["tenthousand.cc"] },
    { slug: "terrasoul_superfoods", name: "Terrasoul Superfoods", officialDomains: ["terrasoul.com"] },
    { slug: "therabody", name: "Therabody", officialDomains: ["therabody.com"] },
    { slug: "thorne", name: "Thorne", officialDomains: ["thorne.com"] },
    { slug: "transparent_labs", name: "Transparent Labs", officialDomains: ["transparentlabs.com"] },
    { slug: "true_nutrition", name: "True Nutrition", officialDomains: ["truenutrition.com"] },
    { slug: "trx", name: "TRX Training", officialDomains: ["trxtraining.com"] },
    { slug: "venum", name: "Venum", officialDomains: ["venum.com"] },
    { slug: "vital_proteins", name: "Vital Proteins", officialDomains: ["vitalproteins.com"] },
  ],

  footer: {
    newsletter: {
      eyebrow: "Performance Club",
      headline: "Train smarter. Recover faster.",
      copy: "Weekly product drops, exclusive member pricing, and science-backed performance briefings — straight to your inbox.",
      placeholder: "Enter your email address",
      cta: "Subscribe",
    },
    backToTop: {
      label: "Back to top",
    },
    columns: [
      {
        title: "Get to Know Us",
        links: [
          { label: "About Athletonic", href: "pages/about.html" },
          { label: "Careers", href: "pages/careers.html" },
          { label: "Press Releases", href: "pages/press.html" },
          { label: "Athletonic Science", href: "pages/science.html" },
          { label: "Sustainability", href: "pages/sustainability.html" },
          { label: "Athletonic Cares", href: "pages/athletonic-cares.html" },
        ],
      },
      {
        title: "Shop With Us",
        links: [
          { label: "Shop all products", href: "pages/catalog.html" },
          { label: "Brand directory", href: "pages/brands.html" },
          { label: "Daily deals", href: "pages/daily-deals.html" },
          { label: "Best sellers", href: "pages/best-sellers.html" },
          { label: "New arrivals", href: "pages/new-arrivals.html" },
          { label: "Gift cards", href: "pages/gift-cards.html" },
        ],
      },
      {
        title: "Make Money With Us",
        links: [
          { label: "Sell Athletonic products", href: "pages/sell-on-athletonic.html" },
          { label: "Become an affiliate", href: "pages/affiliate.html" },
          { label: "Advertise with Athletonic", href: "pages/advertise.html" },
          { label: "Vendor & supply partners", href: "pages/vendor.html" },
          { label: "Athletonic for Coaches", href: "pages/coaches.html" },
          { label: "Athletonic for Gyms", href: "pages/gyms.html" },
        ],
      },
      {
        title: "Let Us Help You",
        links: [
          { label: "Your account", href: "pages/account.html" },
          { label: "Your orders", href: "pages/order-tracking.html" },
          { label: "Shipping rates & policies", href: "pages/shipping.html" },
          { label: "Returns & replacements", href: "pages/returns.html" },
          { label: "Help center", href: "pages/help.html" },
          { label: "Contact us", href: "pages/contact.html" },
        ],
      },
    ],
    locale: {
      language: { label: "Language", value: "English" },
      currency: { label: "Currency", value: "USD — $" },
      country: { label: "Ship to", value: "United States" },
    },
    megaGrid: [
      {
        title: "Supplements",
        links: [
          { label: "Protein", href: "pages/protein.html" },
          { label: "Creatine", href: "pages/creatine.html" },
          { label: "Pre-workout", href: "pages/pre-workout.html" },
          { label: "Hydration & electrolytes", href: "pages/hydration.html" },
          { label: "Vitamins & daily health", href: "pages/vitamins.html" },
          { label: "Greens & superfoods", href: "pages/greens.html" },
          { label: "Bars, shakes & meals", href: "pages/bars-shakes.html" },
        ],
      },
      {
        title: "Recovery & Sleep",
        links: [
          { label: "Recovery devices", href: "pages/recovery.html" },
          { label: "Sleep recovery", href: "pages/sleep.html" },
          { label: "Massage & mobility", href: "pages/massage-mobility.html" },
          { label: "Compression", href: "pages/compression.html" },
          { label: "Cold therapy", href: "pages/cold-therapy.html" },
          { label: "Sleep supplements", href: "pages/sleep-supplements.html" },
        ],
      },
      {
        title: "Goals",
        links: [
          { label: "Build muscle", href: "pages/build-muscle.html" },
          { label: "Lose fat", href: "pages/lose-fat.html" },
          { label: "Endurance", href: "pages/endurance.html" },
          { label: "Daily wellness", href: "pages/daily-wellness.html" },
          { label: "Women's health", href: "pages/womens-health.html" },
          { label: "Energy & focus", href: "pages/energy-focus.html" },
        ],
      },
      {
        title: "Apparel & Gear",
        links: [
          { label: "Training apparel", href: "pages/training-apparel.html" },
          { label: "Footwear", href: "pages/footwear.html" },
          { label: "Accessories", href: "pages/accessories.html" },
          { label: "Bags", href: "pages/bags.html" },
          { label: "Lifting gear", href: "pages/lifting-gear.html" },
          { label: "Combat sports", href: "pages/combat-sports.html" },
        ],
      },
      {
        title: "Featured Brands",
        // Populated at render-time from featuredBrandSlugs[:6]
        linksFromFeaturedBrands: 6,
      },
    ],
    legal: {
      links: [
        { label: "Conditions of Use", href: "pages/conditions-of-use.html" },
        { label: "Privacy Notice", href: "pages/privacy.html" },
        { label: "Your Ads Privacy Choices", href: "pages/ads-privacy-choices.html" },
        { label: "Cookie Preferences", href: "pages/cookie-preferences.html" },
        { label: "Accessibility", href: "pages/accessibility.html" },
        { label: "Do Not Sell My Personal Information", href: "pages/do-not-sell.html" },
      ],
      copyright: "© 2026 Athletonic Marketplace, Inc. All rights reserved.",
    },
  },
};
